# SonarQube Configuration for Sistema de Pedidos Restaurante
sonar.projectKey=sofka-taller-4_sistema-de-pedidos-restaurante
sonar.organization=osp1n4

sonar.projectName=sistema-de-pedidos-restaurante
sonar.projectVersion=1.0

sonar.sources=api-gateway/src,orders-producer-node/src,orders-producer-python/app,orders-producer-frontend/src
sonar.tests=api-gateway/tests,orders-producer-node/src/__tests__,orders-producer-frontend/src/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/test-utils/**,**/scripts/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/test_*.py

# Coverage
sonar.javascript.lcov.reportPaths=orders-producer-frontend/coverage/lcov.info,api-gateway/coverage/lcov.info,orders-producer-node/coverage/lcov.info
sonar.python.coverage.reportPaths=orders-producer-python/coverage.xml
sonar.coverage.exclusions=

sonar.sourceEncoding=UTF-8
sonar.python.version=3.9,3.10,3.11